# Generated by Django 6.0 on 2025-12-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_video_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(auto_created=True, blank=True, max_length=20, unique=True),
        ),
    ]
